#!/usr/bin/env python3
"""Turn binary PBM (P4) bitmaps into LVGL 9 I1 image descriptors."""

import argparse
import pathlib
import sys

PALETTE = (0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF)


def read_pbm(path):
    data = path.read_bytes()
    if not data.startswith(b"P4"):
        sys.exit(f"{path}: not a binary PBM (P4)")

    fields = []
    i = 2
    while len(fields) < 2:
        if i >= len(data):
            sys.exit(f"{path}: truncated header")
        if data[i : i + 1].isspace():
            i += 1
            continue
        if data[i : i + 1] == b"#":
            while i < len(data) and data[i] != 0x0A:
                i += 1
            continue
        j = i
        while j < len(data) and not data[j : j + 1].isspace():
            j += 1
        fields.append(int(data[i:j]))
        i = j
    i += 1

    width, height = fields
    stride = (width + 7) // 8
    body = data[i : i + stride * height]
    if len(body) != stride * height:
        sys.exit(f"{path}: body is {len(body)} bytes, expected {stride * height}")
    return width, height, stride, body


def invert_body(width, height, stride, body):
    tail = width % 8
    keep = 0xFF if tail == 0 else (0xFF << (8 - tail)) & 0xFF

    out = bytearray(len(body))
    for row in range(height):
        base = row * stride
        for col in range(stride):
            mask = keep if col == stride - 1 else 0xFF
            out[base + col] = (body[base + col] ^ 0xFF) & mask
    return bytes(out)


def emit_image(out, symbol, width, height, stride, body, static):
    qualifier = "static " if static else ""
    payload = bytes(PALETTE) + body

    out.write(f"{qualifier}const uint8_t {symbol}_map[] = {{\n")
    for offset in range(0, len(payload), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in payload[offset : offset + 12])
        out.write(f"    {chunk},\n")
    out.write("};\n\n")

    out.write(f"{qualifier}const lv_image_dsc_t {symbol} = {{\n")
    out.write("    .header.magic = LV_IMAGE_HEADER_MAGIC,\n")
    out.write("    .header.cf = LV_COLOR_FORMAT_I1,\n")
    out.write("    .header.flags = 0,\n")
    out.write(f"    .header.w = {width},\n")
    out.write(f"    .header.h = {height},\n")
    out.write(f"    .header.stride = {stride},\n")
    out.write(f"    .data_size = sizeof({symbol}_map),\n")
    out.write(f"    .data = {symbol}_map,\n")
    out.write("};\n\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--symbol", required=True, help="base C identifier")
    parser.add_argument(
        "--array",
        help="emit a frame pointer array under this name, for lv_animimg_set_src",
    )
    parser.add_argument(
        "--invert", action="store_true", help="flip pixel bits before emitting"
    )
    parser.add_argument("pbm", nargs="+", type=pathlib.Path)
    args = parser.parse_args()

    if args.array is None and len(args.pbm) != 1:
        sys.exit("--array is required when converting more than one image")

    out = sys.stdout
    out.write("/* Generated by packages/corne-screen-assets. Do not edit. */\n\n")
    out.write("#include <lvgl.h>\n#include <stddef.h>\n#include <stdint.h>\n\n")

    names = []
    for index, path in enumerate(sorted(args.pbm)):
        symbol = args.symbol if args.array is None else f"{args.symbol}_{index:02d}"
        width, height, stride, body = read_pbm(path)
        if args.invert:
            body = invert_body(width, height, stride, body)
        emit_image(out, symbol, width, height, stride, body, args.array is not None)
        names.append(symbol)

    if args.array:
        out.write(f"const void *{args.array}[] = {{\n")
        for name in names:
            out.write(f"    &{name},\n")
        out.write("};\n\n")
        out.write(
            f"const size_t {args.array}_count = "
            f"sizeof({args.array}) / sizeof({args.array}[0]);\n"
        )


if __name__ == "__main__":
    main()
