name: "flake-update" 
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
  schedule: 
    - cron: '08 10 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check

      - uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Apply automatic changes
          branch: ${{ github.head_ref }}

          # Optional git params
          commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          file_pattern: src/\*.js
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
